<?php


namespace mgen;


class RepositoryFile extends CommonFile
{
    private $struct;

    public function setStruct($struct)
    {
        $this->struct = $struct;
    }

    public function generate()
    {
        $content = ["<?php", "/*", " * This file was generated by modelGen", " * VERSION: {$this->modelHash}", " * https://github.com/alexshadie/modelGen", " */", ""];
        if ($this->namespace) {
            $content[] = "namespace {$this->namespace};";
            $content[] = "";
        }

        $content[] = "use alexshadie\dbwrapper\DBInterface;\n";

        $content[] = "class {$this->name}Repository \n{";

        $content[] = S . "/** @var DBInterface */";
        $content[] = S . "private \$db;\n";

        $content[] = S . "/**";
        $content[] = S . " * Constructor";
        $content[] = S . " * @var DBInterface \$db";
        $content[] = S . " */";
        $content[] = S . "public function __construct(DBInterface \$db)";
        $content[] = S . "{";
        $content[] = S . S . "\$this->db = \$db;";
        $content[] = S . "}";
        $content[] = "";

        $content[] = $this->getCrud();

        $content[] = "}\n";

        return join("\n", $content);
    }

    public function getCrud()
    {
        $content = [S . "/* CRUD */", ""];

        return join("\n", $content);
    }

}