<?php


namespace mgen;


class ServiceFile extends CommonFile
{
    private $struct;

    public function setStruct($struct)
    {
        $this->struct = $struct;
    }

    public function generate()
    {
        $content = ["<?php", "/*", " * This file was generated by modelGen", " * VERSION: {$this->modelHash}", " * https://github.com/alexshadie/modelGen", " */", ""];
        if ($this->namespace) {
            $content[] = "namespace {$this->namespace};";
            $content[] = "";
        }

        $content[] = "class {$this->name}Service \n{";

        $content[] = S . "/** @var {$this->name}Repository */";
        $content[] = S . "private \$repo;\n";

        $content[] = S . "/**";
        $content[] = S . " * Constructor";
        $content[] = S . " * @var {$this->name}Repository \$repo";
        $content[] = S . " */";
        $content[] = S . "public function __construct({$this->name}Repository \$repo)";
        $content[] = S . "{";
        $content[] = S . S . "\$this->repo = \$repo;";
        $content[] = S . "}";
        $content[] = "";

        $content[] = "}\n";

        return join("\n", $content);
    }

}