<?php

namespace mgen;

class SQLFile extends CommonFile
{
    public function generate()
    {

        $file = [
            "-- This file was generated by modelGen",
            "-- VERSION: {$this->modelHash}",
            "-- https://github.com/alexshadie/modelGen",
            "CREATE TABLE " . Helper::camelCaseToUnderscores($this->name) . " (",
        ];
        $file[] = $this->buildFields();
        $file[] = ");";
        $file[] = "";
        return join("\n", $file);
    }

    private function buildFields()
    {
        $sqlFields = [];
        foreach ($this->fields as $field => $type) {
            $t = new Type($type);
            $sqlFields[] = S . $t->getSQLName($field);
            // TODO: Add defaults support
        }
        return join(",\n", $sqlFields);
    }

}